runtime: nodejs10

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'strapi'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: '8ELHns62aPh25dpe'
  INSTANCE_CONNECTION_NAME: 'utbeast:europe-west1:utb-postgresql'

beta_settings:
  cloud_sql_instances: 'utbeast:europe-west1:utb-postgresql'